name: Continuous Integration

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - "**/README.md"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AP_SSID: placeholder
  AP_PASS: placeholder

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        action:
          - command: build
            args: --release
          - command: fmt
            args: --all -- --check --color always
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: esp-rs/xtensa-toolchain@v1.6
        with:
          default: true
          buildtargets: esp32s3
          ldproxy: true
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
      - name: Download pico.min.css
        if: matrix.action.command == 'build'
        run: |
          mkdir -p web/static
          curl -sL https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css \
            -o web/static/pico.min.css
      - name: Run command
        run: cargo ${{ matrix.action.command }} ${{ matrix.action.args }}
